### ISSUE TITLE
What's the browser support?

### ISSUE THREAD

**Issue by bkuhl** [btford/angular-dragon-drop#17]
Can you provide some information on what browsers are supported for this?  I'm considering using it on a project, but want to ensure it'll work with IE 9+

**Comment by benjamincharity** [comment]
Just a quick look running the example.html it seemed to work in IE9+ for me. 

IE8 kind of worked. It would drag but not remove from the value from the first object when added to the second. The value also seemed to appear down in the dom rather than being dragged along with the mouse.

**Comment by btford** [comment]
I am only targeting the most recent version of each major browser. This doesn't mean that it won't work on other browsers, but rather I am not going to test them myself.
