### ISSUE TITLE
Add support for ng-filter

### ISSUE THREAD

**Issue by davisford** [btford/angular-dragon-drop#23]
e.g. to support something like this:

``` html
<input type='text' ng-model='search'>
<ul btf-dragon="val in things | filter:search">
   <li> {{val}} </li>
</ul>
```

I saw there were some forks -- a few of which attempt to add support for sorting or the `orderBy` filter, but I think this directive could really benefit from generic `ng-filter` support.  If I resolve it myself, I'll send a pr for consideration; if anyone has already added support for it, I'd love to see your implementation.

**Comment by davisford** [comment]
Scratch that -- I should have just tried it ;)  It already works.

**Comment by aaronfrost** [comment]
Yeah. It just take the btg-dragon content and processes it as an ng-repeat. So anything that is legit in an ng-repeat will be legit in the btf-dragon.

**Comment by davisford** [comment]
Were you able to get `orderBy` to work?
